// Settings
pref('extensions.tbchatnotification.shownotification', true);
pref('extensions.tbchatnotification.showbody', false);
pref('extensions.tbchatnotification.playsound', false);
pref('extensions.tbchatnotification.soundfile', '');
pref('extensions.tbchatnotification.playsoundfocused', false);
pref('extensions.tbchatnotification.trayicon', false);
pref('extensions.tbchatnotification.flashicon', false);
pref('extensions.tbchatnotification.allincoming', false);
// --------
pref('extensions.tbchatnotification.versiondetect', false);
